name: Deploy feature branches to nonproduction bucket

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: building jar file
        run: jar cfme Main.jar Manifest.txt HelloWorld.Main HelloWorld/Main.class
      
