name: Deploy feature branches to nonproduction bucket

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: building jar file
        run: |
          javac HelloWorld/Main.java
          java -cp . HelloWorld.Main
          jar cfme Main.jar Manifest.txt HelloWorld.Main HelloWorld/Main.class
          ls
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
          
          
      - name: Create zip bundle
        run: |
          Main.jar
          zip -r ../${{ github.sha }}.zip .
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
         
