name: Deploy feature branches to nonproduction bucket

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: building jar file
        run: |
          javac HelloWorld/Main.java
          java -cp . HelloWorld.Main
          jar cfme Main.jar Manifest.txt HelloWorld.Main HelloWorld/Main.class
         
          
          
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: Main.jar
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.SSH_DIR }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
