name: Deploy feature branches to nonproduction bucket

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: building jar file
        run: |
          javac HelloWorld/Main.java
          java -cp . HelloWorld.Main
          jar cfme Main.jar Manifest.txt HelloWorld.Main HelloWorld/Main.class
          ls
          
      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml
          mkdir staging && cp target/*.jar staging
          
          
          
          
      - name: Step 4 - Set up a cache for Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
          
      - name: Create zip bundle
        run: |
          zip -r ../${{ github.sha }}.zip .
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
         
